services:
  - type: web
    name: churn-predictor
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python churn.py sample.csv --min_features 5
    plan: starter
