# services:
#   - type: web
#     name: churn-predictor
#     env: docker
#     dockerfilePath: ./Dockerfile
#     plan: starter
services:
  - type: web
    name: churn-api
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: starter
